### ISSUE TITLE
The ifd score is affected by the prompt

### ISSUE THREAD

**Issue by lihongxiacream** [tianyi-lab/Cherry_LLM#22]
If I modify the template, all the calculated IFD values will be greater than 1
From this
    "prompt_input": (
        "Below is an instruction that describes a task, paired with an input that provides further context. "
        "Write a response that appropriately completes the request.\n\n"
        "### Instruction:\n{instruction}\n\n### Input:\n{input}\n\n### Response:"
    ),
to
    "prompt_input": (
        "Below is an instruction that describes a task, paired with an input that provides further context. "
        "Write a response that appropriately completes the request.\n\n"
        "<|im_start|>system\n{instruction}<|im_end|>\n<|im_start|>user\n{input}<|im_end|>\n<|im_start|>assistant\n"
    )

**Comment by MingLiiii** [comment]
Thank you for your interest in our work!
When you use a template that is unfamiliar to the base model, the IFD scores will increase as the overall formatted instructions are hard for the base model to understand. 

Thus:
1. You need to train a pre-experienced model, which is what exactly Cherry LLM does.
2. Or you can directly remove the templates, which is what Superfiltering does. Please feel free to take a look at Superfiltering's implementation.
